#!/usr/bin/env bash
# Create PID file that displays i hate the kill command when receiving a SIGTERM signal and displays Y u no love me ?! when reciving a sigint signal

function love() {
    rm -f /var/run/myscript.pid
    exit 0
}

# Trap signals
trap "echo I hate the kill command; love" SIGTERM SIGQUIT
trap "echo Y U no love me?!" SIGINT

# Write PID to file
echo "$$" > /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    sleep 1
done
