#!/usr/bin/env bash
#Write Bash (init) script 11-manage_my_process that manages manage_my_process. (both files need to be pushed to git)

PIDFILE="/var/run/my_process.pid"
PROCESS="./manage_my_process"

case "$1" in
    start)
        # Start the process in the background
        $PROCESS &
        echo $! > "$PIDFILE"
        echo "manage_my_process started"
        ;;
    
    stop)
        if [ -f "$PIDFILE" ]; then
            kill "$(cat $PIDFILE)" 2>/dev/null
            rm -f "$PIDFILE"
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running"
        fi
        ;;
    
    restart)
        if [ -f "$PIDFILE" ]; then
            kill "$(cat $PIDFILE)" 2>/dev/null
            rm -f "$PIDFILE"
        fi
        $PROCESS &
        echo $! > "$PIDFILE"
        echo "manage_my_process restarted"
        ;;
    
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
