#!/usr/bin/env bash
#a script that To infinity and beyond with sleep 2 iteration and I am Invincible!!! when receiving a SIGTERM signal
trap "echo 'I am invincible!!!'; exit 0" SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done

